"""empty message

Revision ID: cf9029685617
Revises: 
Create Date: 2017-12-06 19:41:39.049680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9029685617'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdivision',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('cypher', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cypher'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('password')
    )
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('subdivision_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['subdivision_id'], ['subdivision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('worksheet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('position_id', sa.INTEGER(), nullable=True),
    sa.Column('academic_title', sa.String(length=45), nullable=True),
    sa.Column('year_of_birth', sa.Date(), nullable=True),
    sa.Column('date_of_dismissal', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=45), nullable=True),
    sa.Column('telephone', sa.String(length=45), nullable=True),
    sa.Column('previous_employment', sa.String(length=45), nullable=True),
    sa.Column('diploma_number', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worksheet')
    op.drop_table('department')
    op.drop_table('user')
    op.drop_table('subdivision')
    # ### end Alembic commands ###
